[settings]
color = false
gpg_verify = true
install_before = "7d" # dependency cooldown (unless specific version specified)
paranoid = true
trusted_config_paths = [
  "~/.config/mise.toml",
  "~/src/csutter/dotfiles/mise.toml"
]

[tools]
claude-code = "latest"
github-cli = "latest"
